apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pal-tracker
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: pal-tracker
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/billkable/pal-tracker
      ref:
        branch: main
  params:
  - name: tekton-pipeline-name
    value: pal-tracker-ci-pipeline
  env:
    - name: GREETING_MESSAGE
      value: "taproom-beta4-public"
