apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: pal-tracker
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: pal-tracker
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      url: https://github.com/billkable/pal-tracker
      ref:
        branch: main